// Generated by CoffeeScript 1.3.1
(function() {
  var errorCallback, successCallback;

  errorCallback = function(e) {
    return console.log(e);
  };

  successCallback = function(v, stream) {
    var goFullscreen;
    goFullscreen = function(elem) {
      if (typeof elem.webkitRequestFullScreen === "function") {
        elem.webkitRequestFullScreen();
      }
      if (typeof elem.mozRequestFullScreen === "function") {
        elem.mozRequestFullScreen();
      }
      return typeof elem.requestFullScreen === "function" ? elem.requestFullScreen() : void 0;
    };
    $(v).hide();
    $('#mirror').html(v);
    $(v).fadeIn(3500);
    $('#fullscreen').fadeIn(2000).click(function() {
      return goFullscreen(v);
    });
    v.addEventListener('click', function() {
      return goFullscreen();
    });
    return v.addEventListener('load', function() {
      return goFullscreen();
    });
  };

  Sinne.getUserVideo(successCallback, errorCallback, {
    id: "vid",
    controls: false
  });

}).call(this);
